name: "helm: publish charts"
on:
  push:
    tags:
      - '*'

permissions:
  contents: write
  pages: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10
      - name: Publish Helm charts
        uses: stefanprodan/helm-gh-pages@master
        with:          
          token: ${{ secrets.GITHUB_TOKEN }}
          charts_dir: k8s/charts
          target_dir: helm
          branch: gh-pages
